[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  # Whitelist safe keys to avoid Netlify secrets scan errors
  SECRETS_SCAN_OMIT_KEYS = "VITE_RAPID_API_URL,VITE_RAPID_API_HOST,VITE_RAPID_API_KEY,VITE_FIREBASE_*"
